### ISSUE TITLE
Also do we put the content in site/wwwroot/webapps? 

### ISSUE THREAD

**Issue by sandakith** [AzureCAT-GSI/DropWizardOnAzure#2]
or in site/wwwroot

**Comment by rsponholtz** [comment]
The web.config should be in D:\home\site\wwwroot.  In the web.config, the instructions have you put in a line that looks like this:
`
    <httpPlatform processPath="%JAVA_HOME%\bin\java.exe"
        arguments="-Djava.net.preferIPv4Stack=true -jar &quot;%HOME%\site\wwwroot\DWOnAzure-1.0-SNAPSHOT.jar&quot;  &quot;%HOME%\site\wwwroot\config.yml&quot;">
    </httpPlatform>
`
this tells the web app to run the jar file in the parameter, and pass the config.yml as a parameter.  If you want to put those somewhere else, you would have to adjust those parameters.

**Comment by sandakith** [comment]
Actually we need term "server" between jar and config? 

We are getting there, now trying to deploy all APIs with the DB. Lets see how it goes.
